"""Regression checks that all analysis API routes share the same decision."""

import numpy as np
from fastapi.testclient import TestClient

from api.main import app


client = TestClient(app)


def _make_bpsk_iq(
    num_bits: int = 256,
    fs: float = 1_000_000.0,
    baud: float = 25_000.0,
    carrier_hz: float = 50_000.0,
) -> bytes:
    rng = np.random.default_rng(42)
    samples_per_symbol = int(fs / baud)
    bits = rng.integers(0, 2, num_bits)
    symbols = np.repeat(np.where(bits == 1, 1.0, -1.0), samples_per_symbol)
    time = np.arange(len(symbols)) / fs
    signal = symbols * np.exp(2j * np.pi * carrier_hz * time)
    noise = 0.01 * (
        rng.standard_normal(len(signal)) + 1j * rng.standard_normal(len(signal))
    )
    return (signal + noise).astype(np.complex64).tobytes()


def _upload(iq_bytes: bytes):
    return {"file": ("consistency.iq", iq_bytes, "application/octet-stream")}


def test_same_iq_has_consistent_modulation_across_process_classify_decode():
    fs = 1_000_000.0
    iq_bytes = _make_bpsk_iq()

    process_response = client.post(
        "/process/file", params={"fs": fs}, files=_upload(iq_bytes)
    )
    classify_response = client.post(
        "/classify/", params={"fs": fs}, files=_upload(iq_bytes)
    )
    decode_response = client.post(
        "/decode/",
        params={
            "fs": fs,
            "fec_scheme": "none",
            "auto_deinterleave": "false",
            "auto_detect_sync": "false",
        },
        files=_upload(iq_bytes),
    )

    assert process_response.status_code == 200, process_response.text
    assert classify_response.status_code == 200, classify_response.text
    assert decode_response.status_code == 200, decode_response.text

    process = process_response.json()
    classify = classify_response.json()
    decode = decode_response.json()

    assert process["modulation"] == classify["modulation"] == decode["modulation"]
    assert process["confidence"] == classify["confidence"] == decode["confidence"]

    # These are generated by the same SignalAnalysis pipeline in all routes.
    # A small tolerance allows for serialization and floating point rounding.
    for key in ("center_frequency_hz", "bandwidth_hz", "baud_rate", "snr_db"):
        process_value = process[key]
        classify_value = classify[key]
        decode_value = decode[key]
        assert np.isfinite(process_value)
        assert np.isfinite(classify_value)
        assert np.isfinite(decode_value)
        assert np.isclose(process_value, classify_value, rtol=1e-6, atol=1e-3), (
            f"/process and /classify disagree for {key}: "
            f"{process_value} vs {classify_value}"
        )
        assert np.isclose(process_value, decode_value, rtol=1e-6, atol=1e-3), (
            f"/process and /decode disagree for {key}: "
            f"{process_value} vs {decode_value}"
        )


def test_parameter_estimates_are_finite_and_consistent_across_repeated_routes():
    """Check /process parameter estimates are stable across repeated requests."""
    fs = 1_000_000.0
    iq_bytes = _make_bpsk_iq()
    outputs = []
    for _ in range(2):
        response = client.post(
            "/process/file", params={"fs": fs}, files=_upload(iq_bytes)
        )
        assert response.status_code == 200, response.text
        outputs.append(response.json())

    keys = ("center_frequency_hz", "bandwidth_hz", "baud_rate", "snr_db")
    for key in keys:
        a, b = outputs[0][key], outputs[1][key]
        assert np.isfinite(a), f"/process returned non-finite {key}: {a}"
        assert np.isfinite(b), f"/process returned non-finite {key}: {b}"
        assert np.isclose(a, b, rtol=1e-6, atol=1e-3), (
            f"Repeated /process calls disagree for {key}: {a} vs {b}"
        )

    # Spectral peak estimation has finite FFT resolution on this 1 MHz capture.
    assert abs(outputs[0]["center_frequency_hz"] - 50_000.0) < 20_000.0
    assert abs(outputs[0]["baud_rate"] - 25_000.0) < 16_000.0
